name: Unit Tests

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'e2e/**'
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'e2e/**'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/Hydrogen

      - name: Cache node modules
        uses: actions/cache@v4
        id: cache-nodemodules
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
            ${{ runner.os }}-

      - name: Install dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run Unit Tests
        run: npm run unit-test:ci

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: test-results/junit-results.xml

      - name: Define Test Result Title
        run: |
          echo "## Test Results" >> $GITHUB_STEP_SUMMARY

      - name: Test Results Report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Unit Tests
          path: test-results/junit-results.xml
          reporter: java-junit
          badge-title: 'tests_results'

      - name: Generate Code Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/todo/cobertura-coverage.xml
          badge: true
          fail_below_min: true
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          format: markdown
          output: both
          thresholds: '60 80'

      - name: Display Coverage Title in Workflow Summary
        run: |
          echo "## Code Coverage" >> $GITHUB_STEP_SUMMARY
          cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

  run-e2e:
    needs: unit-test
    if: ${{ needs.unit-test.result == 'success' }}
    uses: ./.github/workflows/e2e-tests.yml
    with:
      TEST_ENV: 'local'
